/**
 * Augments the ambient CloudflareEnv interface with runtime bindings that are
 * intentionally not hand-written into cloudflare-env.d.ts. That file is
 * regenerated by `npm run cf-typegen`, while these declarations must survive
 * regeneration.
 */
declare global {
  interface CloudflareEnv {
    /** Discord webhook URL the quote handler posts new leads to. */
    DISCORD_WEBHOOK_URL: string;
    /**
     * Optional D1 database used by the anonymous visitor counter. The site
     * intentionally degrades to an unavailable counter when the binding has
     * not been provisioned rather than blocking page rendering/deployment.
     */
    VISITOR_DB?: D1Database;
  }
}

export {};
